datagrid:
    attachment-grid:
        source:
            type: orm
            query:
                select:
                    - attachment as att
                    - attachment.comment as comment
                    - file.originalFilename as originalFilename
                    - file.fileSize as fileSize
                    - file.createdAt as createdAt
                from:
                    - { table: 'OroAttachmentBundle:Attachment', alias: attachment }
                join:
                    left:
                        - { join: attachment.file, alias: file }
                where:
                    and:
                      - entity.id = :entityId # entity with alias 'entity' sets in event listener
        columns:
            originalFilename:
                type: twig
                label: oro.attachment.file.filename.label
                frontend_type: html
                template: OroAttachmentBundle:Attachment:Datagrid/Property/allachmentLink.html.twig
            fileSize:
                label: oro.attachment.file.file_size.label
                type: twig
                frontend_type: html
                template: OroAttachmentBundle:Attachment:Datagrid/Property/fileSize.html.twig
            createdAt:
                label: oro.attachment.file.created_at.label
                frontend_type: datetime
            comment:
                label: oro.attachment.comment.label
