datagrid:
    attachment-grid:
        source:
            type: orm
            query:
                select:
                    - attachment
                from:
                    - { table: 'OroAttachmentBundle:Attachment', alias: attachment }
                where:
                    and:
                      - e.id = :entityId # entity with aliae 'e' sets in event listener
        columns:
            originalFilename:
                type: twig
                label: oro.attachment.filename.label
                frontend_type: html
                template: OroAttachmentBundle:Attachment:Datagrid/Property/allachmentLink.html.twig
                context: ~ # set from buildBefore in event listener
            fileSize:
                label: oro.attachment.file_size.label
            createdAt:
                label: oro.attachment.created_at.label
                frontend_type: datetime
            comment:
                label: comment.label