oro_entity_config:
    attachment:
        field:
            items:
                attachment:
                    options:
                        allowed_type:       [attachment, attachmentImage]
                        auditable:          false
                    form:
                        type:               oro_attachment_config
                        options:
                            block:          entity
                            subblock:       properties

                maxsize:
                    options:
                        allowed_type:   [attachment, attachmentImage]
                        auditable:      false
                    constraints:
                        - NotBlank:  ~
                        - Type:      integer
                        - Range:
                            min:     1
                    form:
                        type:           integer
                        options:
                            required:   true
                            label:      File size
                            block:      entity
                            subblock:   properties
                            empty_data: 1
                            tooltip:    Max allowed file size to upload in MB.

                width:
                    options:
                        allowed_type:   [attachmentImage]
                        auditable:      false
                    constraints:
                        - Type:
                            type: int
                    form:
                        type:           integer
                        options:
                            required:   false
                            label:      Thumbnail width
                            block:      entity
                            subblock:   properties
                            empty_data: 32
                            tooltip:    Thumbnail width in PX.

                height:
                    options:
                        allowed_type:   [attachmentImage]
                        auditable:      false
                    constraints:
                        - Type:
                            type: int
                    form:
                        type:           integer
                        options:
                            required:   false
                            label:      Thumbnail height
                            block:      entity
                            subblock:   properties
                            empty_data: 32
                            tooltip:    Thumbnail height in PX.

