oro_entity_config:
    attachment:
        field:
            items:
                attachment:
                    options:
                        allowed_type:       [attachment]
                        auditable:          false
                    form:
                        type:               oro_attachment_config
                        options:
                            block:          entity
                            subblock:       properties

                filetype:
                    options:
                        allowed_type:   [attachment]
                        auditable:      false
                    constraints:
                        - NotBlank: ~
                    form:
                        type:           choice
                        options:
                            required:   true
                            choices:
                                bmp: Bmp
                                gif: Gif
                                jpg: Jpg
                                png: Png
                                doc: Doc
                                xls: Xls
                                pdf: PDF
                            label:      File Types
                            multiple:   true
                            block:      entity
                            subblock:   properties
                            tooltip:    Allowed file types for upload.

                maxsize:
                    options:
                        allowed_type:   [attachment]
                        auditable:      false
                    constraints:
                        - NotBlank:  ~
                        - Type:      integer
                        - Range:
                            min:     1
                    form:
                        type:           integer
                        options:
                            required:   true
                            label:      File size
                            block:      entity
                            subblock:   properties
                            tooltip:    Max allowed file size to upload in MB.
