parameters:
    oro_attachment.form.type.attachment_config.class: Oro\Bundle\AttachmentBundle\Form\Type\AttachmentConfigType

services:
    oro_attachment.form.type.attachment_config:
        class: %oro_attachment.form.type.attachment_config.class%
        arguments:
            - @oro_entity_config.config_manager
        tags:
            - { name: form.type, alias: oro_attachment_config }
