parameters:
    oro_attachment.form.type.attachment_config.class: Oro\Bundle\AttachmentBundle\Form\Type\AttachmentConfigType
    oro_attachment.form.type.file.class:              Oro\Bundle\AttachmentBundle\Form\Type\FileType
    oro_attachment.form.type.image.class:             Oro\Bundle\AttachmentBundle\Form\Type\ImageType
    oro_attachment.form.file_subscriber.class:        Oro\Bundle\AttachmentBundle\Form\EventSubscriber\FileSubscriber
    oro_attachment.validator.file_config_validator.class: Oro\Bundle\AttachmentBundle\Validator\ConfigFileValidator

    oro_attachment.form.handler.attachment.class:     Oro\Bundle\AttachmentBundle\Form\Handler\AttachmentHandler

services:
    oro_attachment.form.type.attachment_config:
        class: %oro_attachment.form.type.attachment_config.class%
        arguments:
            - @oro_entity_config.config_manager
        tags:
            - { name: form.type, alias: oro_attachment_config }

    oro_attachment.form.type.file:
        class: %oro_attachment.form.type.file.class%
        calls:
            - [setEventSubscriber, [@oro_attachment.form.file_subscriber]]
        tags:
            - { name: form.type, alias: oro_file }

    oro_attachment.form.type.image:
        class: %oro_attachment.form.type.image.class%
        tags:
            - { name: form.type, alias: oro_image }

    oro_attachment.form.file_subscriber:
        class: %oro_attachment.form.file_subscriber.class%
        arguments: [@oro_attachment.validator.file_config_validator]

    oro_attachment.validator.file_config_validator:
        class: %oro_attachment.validator.file_config_validator.class%
        arguments: [@validator, @oro_entity_config.config_manager, @oro_config.user]

    oro_attachment.form.attachment:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - ''
            - 'oro_file'

    oro_attachment.form.handler.attachment:
        class: %oro_attachment.form.handler.attachment.class%
        scope: request
        arguments:
            - @oro_attachment.form.attachment
            - @request
            - @doctrine.orm.entity_manager
