placeholders:
    view_navButtons_before:
        items:
            oro_add_attachment_button:
                order: -100

    view_content_data_additional_information:
        items:
            oro_attachments:
                order: 100

items:
    oro_add_attachment_button:
        template: OroAttachmentBundle:Attachment:addButton.html.twig
        applicable: @oro_attachment.placeholder.filter->isAttachmentAssociationEnabled($entity$)

    oro_attachments:
        template: OroAttachmentBundle:Attachment:attachments.html.twig
        applicable: @oro_attachment.placeholder.filter->isAttachmentAssociationEnabled($entity$)
