services:
    oro_attachment.api.customize_loaded_data.compute_file_content:
        class: Oro\Bundle\AttachmentBundle\Api\Processor\ComputeFileContent
        arguments:
            - '@oro_attachment.file_manager'
            - '@logger'
        tags:
            - { name: oro.api.processor, action: customize_loaded_data, class: Oro\Bundle\AttachmentBundle\Entity\File }
            - { name: monolog.logger, channel: api }

    oro_attachment.api.add_file_content_form_listener:
        class: Oro\Bundle\AttachmentBundle\Api\Processor\AddFileContentFormListener
        arguments:
            - '@oro_attachment.file_manager'
        tags:
            - { name: oro.api.processor, action: create, group: transform_data, class: Oro\Bundle\AttachmentBundle\Entity\File, priority: 90 }
            - { name: oro.api.processor, action: update, group: transform_data, class: Oro\Bundle\AttachmentBundle\Entity\File, priority: 90 }

    oro_attachment.api.add_inverse_attachment_association:
        class: Oro\Bundle\ApiBundle\Processor\Config\Shared\AddInverseToOneAssociation
        arguments:
            - '@oro_entity_config.provider.extend'
            - '@oro_api.doctrine_helper'
            - '@oro_api.value_normalizer'
        calls:
            - [setAssociationClass, ['Oro\Bundle\AttachmentBundle\Entity\Attachment']]
        tags:
            - { name: oro.api.processor, action: get_config, extra: !identifier_fields_only&definition, priority: -29 }

    oro_attachment.api.add_inverse_file_association:
        class: Oro\Bundle\ApiBundle\Processor\Config\Shared\AddInverseToOneAssociation
        arguments:
            - '@oro_entity_config.provider.extend'
            - '@oro_api.doctrine_helper'
            - '@oro_api.value_normalizer'
        calls:
            - [setAssociationClass, ['Oro\Bundle\AttachmentBundle\Entity\File']]
        tags:
            - { name: oro.api.processor, action: get_config, extra: !identifier_fields_only&definition, priority: -29 }
