parameters:
    oro_attachment.manager.attachment_manager.class:     Oro\Bundle\AttachmentBundle\Manager\AttachmentManager
    oro_attachment.listener.attachment_listener.class:   Oro\Bundle\AttachmentBundle\EventListener\AttachmentListener
    oro_attachment.twig.attachment_extension.class:      Oro\Bundle\AttachmentBundle\Twig\AttachmentExtension

    oro_attachment.entity_config_dumper.extension.class:  Oro\Bundle\AttachmentBundle\Tools\AttachmentEntityConfigDumperExtension
    oro_attachment.config_dumper.extension.class:         Oro\Bundle\AttachmentBundle\Tools\AttachmentsConfigDumperExtension
    oro_attachment.attachments.generator.extension.class: Oro\Bundle\AttachmentBundle\Tools\AttachmentsGeneratorExtension
    oro_attachment.migration.extension.attachment.class:  Oro\Bundle\AttachmentBundle\Migration\Extension\AttachmentExtension

    oro_attachment.serializer.attachment_normalizer:     Oro\Bundle\AttachmentBundle\ImportExport\AttachmentNormalizer
    oro_attachment.placeholder.filter.class:             Oro\Bundle\AttachmentBundle\Placeholder\PlaceholderFilter
    oro_attachment.attachment_grid_listener:             Oro\Bundle\AttachmentBundle\EventListener\AttachmentGridListener
services:
    oro_attachment.manager:
        class: %oro_attachment.manager.attachment_manager.class%
        arguments: [@knp_gaufrette.filesystem_map, @router, %oro_attachment.files%]

    oro_attachment.listener.attachment_listener:
        class: %oro_attachment.listener.attachment_listener.class%
        arguments: [@oro_attachment.manager]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }

    oro_attachment.twig.attachment_extension:
        class: %oro_attachment.twig.attachment_extension.class%
        arguments: [@oro_attachment.manager, @oro_entity_config.config_manager, @doctrine.orm.entity_manager]
        tags:
            - { name: twig.extension }

    oro_attachment.entity_config_dumper.extension:
        class: %oro_attachment.entity_config_dumper.extension.class%
        arguments:
            - @oro_entity_extend.relation_builder
        tags:
            - { name: oro_entity_extend.entity_config_dumper_extension }

    oro_attachment.attachments.config_dumper.extension:
        class: %oro_attachment.config_dumper.extension.class%
        arguments:
            - @oro_entity_extend.relation_builder
            - @oro_entity_extend.association_builder
        tags:
            - { name: oro_entity_extend.entity_config_dumper_extension }

    oro_attachment.attachments.generator.extension:
        class: %oro_attachment.attachments.generator.extension.class%
        tags:
            - { name: oro_entity_extend.entity_generator_extension }


    oro_attachment.migration.extension.attachment:
        class: %oro_attachment.migration.extension.attachment.class%
        arguments:
            - @oro_entity_extend.migration.options_manager
        tags:
            - { name: oro_migration.extension, extension_name: attachment }

    oro_attachment.serializer.attachment_normalizer:
        class: %oro_attachment.serializer.attachment_normalizer%
        calls:
            - [setAttachmentManager, [@oro_attachment.manager]]
            - [setValidator, [@oro_attachment.validator.file_config_validator]]
        tags:
            - { name: oro_importexport.normalizer}

    oro_attachment.placeholder.filter:
        class: %oro_attachment.placeholder.filter.class%
        arguments:
            - @oro_entity_config.provider.attachment

    oro_attachment.event_listener.attachment_grid_listener:
        class: %oro_attachment.attachment_grid_listener%
        arguments:
            - [entityId]
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.after.attachment-grid, method: onBuildAfter }
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.before.attachment-grid, method: onBuildBefore }