parameters:
    oro_attachment.manager.attachment_manager.class:     Oro\Bundle\AttachmentBundle\Manager\AttachmentManager
    oro_attachment.listener.attachment_listener.class:   Oro\Bundle\AttachmentBundle\EventListener\AttachmentListener
    oro_attachment.twig.attachment_extension.class:      Oro\Bundle\AttachmentBundle\Twig\AttachmentExtension

    oro_attachment.entity_extend.dumper_extension.class: Oro\Bundle\AttachmentBundle\Tools\AttachmentExtendConfigDumperExtension
    oro_attachment.migration.extension.attachment.class: Oro\Bundle\AttachmentBundle\Migration\Extension\AttachmentExtension

    oro_attachment.serializer.attachment_normalizer:     Oro\Bundle\AttachmentBundle\ImportExport\AttachmentNormalizer

services:
    oro_attachment.manager:
        class: %oro_attachment.manager.attachment_manager.class%
        arguments: [@knp_gaufrette.filesystem_map, @router, %oro_attachment.files%]

    oro_attachment.listener.attachment_listener:
        class: %oro_attachment.listener.attachment_listener.class%
        arguments: [@oro_attachment.manager]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }

    oro_attachment.twig.attachment_extension:
        class: %oro_attachment.twig.attachment_extension.class%
        arguments: [@oro_attachment.manager, @oro_entity_config.config_manager]
        tags:
            - { name: twig.extension }

    oro_attachment.entity_extend.dumper_extension:
        class: %oro_attachment.entity_extend.dumper_extension.class%
        arguments:
            - @oro_entity_config.config_manager
        tags:
            - { name: oro_entity_extend.dumper_extension }

    oro_attachment.migration.extension.attachment:
        class: %oro_attachment.migration.extension.attachment.class%
        arguments:
            - @oro_entity_extend.migration.options_manager
        tags:
            - { name: oro_migration.extension, extension_name: attachment }

    oro_attachment.serializer.attachment_normalizer:
        class: %oro_attachment.serializer.attachment_normalizer%
        tags:
            - { name: oro_importexport.normalizer}
