oro_system_configuration:
    groups:
        attachment_settings:
            icon:   icon-file
            title:  oro.attachment.config.attachment.label
        attachment_mime_types_settings:
            title:  oro.attachment.config.mime_types.label
    fields:
        oro_attachment.upload_mime_types:
            type: textarea
            options:
                label: oro.attachment.config.upload_mime_types.label
        oro_attachment.upload_image_mime_types:
            type: textarea
            options:
                label: oro.attachment.config.upload_image_mime_types.label
    tree:
        system_configuration:
            platform:
                children:
                    general_setup:
                        children:
                            attachment_settings:
                                priority: -10
                                children:
                                    attachment_mime_types_settings:
                                        children:
                                            - oro_attachment.upload_mime_types
                                            - oro_attachment.upload_image_mime_types
