knp_gaufrette:
    adapters:
        attachments:
            local:
                directory: '%kernel.root_dir%/%oro_attachment.attachments_dir%'
    filesystems:
        attachments:
            adapter:    attachments
            alias:      attachments_filesystem
